apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: tusharag/user-service:1.0.1-RELEASE
        ports:
        - containerPort: 8000
        env:
        - name: JAEGER_HOST
          value: jaeger-agent
        - name: RDS_HOSTNAME
          value: mysql-service
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-name
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: user
  type: ClusterIP