apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: tusharag/order-service:1.0.1-RELEASE
        ports:
        - containerPort: 8001
        env:
        - name: JAEGER_HOST
          value: jaeger-agent
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
  - port: 8001
    protocol: TCP
  selector:
    app: order
  type: ClusterIP